### ISSUE TITLE
should this repo be relocated to creativescala org?

### ISSUE THREAD

**Issue by SethTisue** [underscoreio/creative-scala#63]
I was puzzled not to find it under https://github.com/creativescala

**Comment by noelwelsh** [comment]
Moving it requires updating Creative Scala. Otherwise the book will point
to a repo that doesn't exist and people will get confused. There is a
branch in Creative Scala where I'm updating the book to use mdoc. When this
is complete I'll be able to build the book again and I can change the URL
in the book.

N.

**Comment by noelwelsh** [comment]
This is done.
